# user testuser7:testuser7
# tenant header
# host https://dev.tenants.aloedev.tacc.cloud
# client create
#     "name": "rsthrtapp",
#     "consumerKey": "k258KfoXvHLor0TyF310QNbria0a",
#     "consumerSecret": "iGG8JW1m3i1ev22k265qvj65Ndwa"


###  client create
POST {{host}}/clients/v2
Authorization: Basic {{user}} {{pass}}
Content-Type: application/x-www-form-urlencoded

clientName=rsthrtapp&description=test client app

###

###  restheart calls to dev api metadata
GET {{host}}/rh/v2/api/metadata
Authorization: Bearer {{token}}
Content-Type: application/json

###

###   create GridFs bucket collection
PUT {{host}}/rh/v2/api/mybucket.files
Authorization: Bearer {{token}}
Content-Type: application/json

###

###   get db
GET {{host}}/rh/v2/api
Authorization: Bearer {{token}}
Content-Type: application/json

###

###   create db
PUT {{host}}/rh/v2/api
Authorization: Bearer {{token}}
Content-Type: application/json

###

###   create collection
PUT {{host}}/rh/v2/api/metadata
Authorization: Bearer {{token}}
Content-Type: application/json

###

###   get coll
GET {{host}}/rh/v2/api/metadata
Authorization: Bearer {{token}}
Content-Type: application/json

###

###    create documnent one
POST {{host}}/rh/v2/api/metadata
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "steve",
  "rating": "cool"
}

###

###   get doc 1
GET {{host}}/rh/v2/api/metadata/5d0956b9028ae24619924e73
Authorization: Bearer {{token}}
Content-Type: application/json

###

###    create documnent two
POST {{host}}/rh/v2/api/metadata
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "mongodb",
  "rating": "cool as well"
}

###

###   get doc 2
GET {{host}}/rh/v2/api/metadata/5c65868eda6a750c18085326
Authorization: Bearer {{token}}
Content-Type: application/json

###

###   get all docs
GET {{host}}/api/metadata
Authorization: Bearer {{token}}
Content-Type: application/json

###


###   get doc 1
GET {{host}}/api/metadata/5c65868eda6a750c18085326
Authorization: Bearer {{token}}
Content-Type: application/json

###

###    find document two
GET {{host}}/api/metadata?filter={'name':'mongodb'}
Authorization: Bearer {{token}}
Content-Type: application/json


###

###    find document one
GET {{host}}/api/metadata?filter={'name':'steve'}
Authorization: Bearer {{token}}
Content-Type: application/json


###


# /${JOB_ID}?status=${JOB_STATUS}&name=${JOB_NAME}&startTime=${JOB_START_TIME}&endTime=${JOB_END_TIME}&submitTime=${JOB_SUBMIT_TIME}&archiveSystem=${JOB_ARCHIVE_SYSTEM}&archivePath=${JOB_ARCHIVE_PATH}&message=${JOB_ERROR}https://de.sciapps.org/notification



# {
#   "exception" : "SystemError",
#   "error" : "SystemError: Warning caught during route execution: Use of uninitialized value in string eq at /home/zlu/project/AgaveWeb/MaizeCode/agavedancer/lib/iPC/SciApps.pm line 1341.\n at /usr/local/lib/perl5/site_perl/5.16.1/Dancer/Hook.pm line 62.\n"
# }