## RESTHeart simple security configuration file.
---
## Configuration for file based Access Manager

## Look at undertow documentation for information about predictates syntax
## http://undertow.io/undertow-docs/undertow-docs-1.3.0/index.html#predicates-attributes-and-handlers
## The special role $unauthenticated allows to give permissions without requiring authentication
permissions:
  # Users with role 'Internal/dev-services-admin' can do anything
  - role: Internal/dev-services-admin
    predicate: path-prefix[path="/"]

  # authenticated vdj user can only GET any resource under the /v1public URI
  - role: Internal/vdj
    predicate: path-prefix[path="/v1public/"] and method[value="GET"]

  # authenticated designsafe user can only GET any resource under the /api URI
  - role: Internal/designsafe
    predicate: path-prefix[path="/api/"] and method[value="GET"]

  # Users with role 'users' can request URI /_logic/csv
  # - role: users
  #   predicate: path["/_logic/csv"]

  # Not authenticated user can only GET any resource under the /publicdb URI
  # - role: $unauthenticated
  #   predicate: path-prefix[path="/publicdb/"] and method[value="GET"]

  # Users with role 'Internal/everyone' can GET any collection or document resource (excluding dbs and _logic )
  # - role: Internal/everyone
  #   predicate: regex[pattern="/.*/.*", value="%R", full-match=true] and method[value="GET"] and not path-prefix[path="/_logic"]

  # Users with role 'users' can do anything on the collection /publicdb/{username}
  # - role: users
  #   predicate: path-template[value="/publicdb/{username}"] and equals[%u, "${username}"]

  # Users with role 'users' can do anything on documents of the collection /publicdb/{username}
  # - role: users
  #   predicate: path-template[value="/publicdb/{username}/{doc}"] and equals[%u, "${username}"]

# Same than previous one, but using regex predicate
# Users with role 'users' can do anything on documents of the collection /publicdb/{username}
#    - role: users
#      predicate: regex[pattern="/publicdb/(.*?)/.*", value="%R", full-match=true] and equals[%u, "${1}"]
